### ISSUE TITLE
Network connection fails after starting agent session

### ISSUE THREAD

**Issue by nrusch** [ilpvfx/interstate_love_song#7]
Hello,

We are experimenting with ILS, and I've got the basic pieces in place and seemingly functioning using the `SimpleMapper` plugin. However, I seem to be running into an issue related to the broker's hand-off of the connection between the client and agent.

I'm using the software client, and after authenticating, the broker is properly triggering a session launch on one of the provided resources (which are IPs of hosts running the PCoIP software agent). The client or broker seemingly connects to the agent, and a PCoIP session is started, but the client then seems to get stuck trying to actually connect to the session, and eventually errors out with the error "The network connection has been lost".

If I directly connect to the IP of the agent host, I can access the session that was previously initiated by the broker, but trying to (re)connect through the broker consistently fails with the same network error.

We have been using direct connections only thus far, so we do not have a connection manager deployed, in case that's relevant. I'm not totally clear on whether a connection manager is required when using a broker; my assumption thus far has been that it is not, but please let me know if it is actually a requirement. Otherwise, I'm wondering if you've encountered this kind of issue at all (we're running everything on CentOS 7.8).

Thank you.

**Comment by nrusch** [comment]
And by the way, thanks for putting such a great project out there! It's looking to be tremendously useful, and the fact that it's built to be extensible from the start promises to be a huge asset.

**Comment by skurmedel** [comment]
Hi, I have a faint recollection that we might've seen this issue. At least we've seen similar issues. I wasn't involved in our final deployment so I'm a bit rusty about potential Teradici clashes.

You might already be familiar with the things I'll describe, but just in case:

A broker session goes through these steps:
- PCOIP-client says hello, gets a response
- PCOIP-client says authenticate, gets a response (may be a rejection response if auth was bad)
- PCOIP-client says get resources, gets a response filled with resources (this is where the mapper comes in)
- PCOIP-client says give me a session on this resource
- Broker asks the resource for a session, and it responds with one (hopefully)
- PCOIP-client gets a session id.
- PCOIP-client says good bye.

After this, the broker is no longer involved and your PCOIP-client connects directly to the resource with the session.

It seems to me, judging by the message your getting, that it's this last step that fails. That might be some kind of configuration issue or some mismatch between ILS and your Teradici resource.

A confusing thing is the messages displayed in the PCOIP-client might be error messages returned by the broker, or by Teradicis stuff. It actually reminded me that we maybe should prefix all broker messages with "(ILS)" or something so it is perfectly clear when ILS is the culprit.

Can you see anything in the log output by ILS itself? The logging in ILS could certainly be better though.

@torsdag Didn't you see something resembling this? How did we get around it?
@smaragden Any ideas?

**Comment by nrusch** [comment]
Thanks for the follow-up @skurmedel. I actually think I've figured out my issue.

The machines that we're testing out have two network interfaces on them (internal and external), and we want to use the IP of the secondary (external) interface for PCoIP connections. However, when establishing a connection using the broker, the agent seems to be returning the IP of the primary network interface as the connection target, which is not visible to the client. Helpfully, the client logs include the XML payloads from the connection handshake requests, so the IP mismatch in the the `<allocate-resource-resp>` message was easy to spot once I knew where to look...

The straightforward workaround for this is to override the `pcoip.client_connection_address` config value on the agent host so the agent returns the external IP with its. However, I think we may also be able to make some small changes to ILS to remap the IP address that gets sent with the `AllocateResourceSuccessResponse` message in a pluggable/customizable way. We'll most likely follow up if/when we get there (assuming the result isn't too ugly), to see if you think the result makes sense to roll back into the main repo.

Oh, just as one final question, do you happen to know what the valid values are for the `<resource-state>` attribute in the `<get-resource-list-resp>` message?

Thanks again,
-Nathan

**Comment by skurmedel** [comment]
Ohh, that's an interesting issue. Glad you found it out.

Not off hand sadly. I know we identified at least two, but they were quite common, and we are interested in looking into it further. It is apparently possible for a broker to mark resources as "unavailable" or something similar which would be extremely usefull.
